const text = [
    `I'm baby farm-to-table plaid wayfarers, bodega boys +1 tilde squid. Viral la croix fashion axe roof party. Hoodie air plant next level, yes plz gastropub gorpcore keffiyeh blackbird spyplane cray DIY. Tumeric iPhone post-ironic, raw denim godard synth whatever DSA palo santo. Kale chips art party drinking vinegar meditation lomo activated charcoal yuccie ugh sartorial keytar synth paleo. Flannel jean shorts bespoke, deep v austin locavore church-key helvetica keytar.`,
    `Aesthetic polaroid palo santo cred tumblr pickled bitters unicorn disrupt single-origin coffee kogi. Shaman knausgaard poke you probably haven't heard of them tbh narwhal forage prism blackbird spyplane vegan. Deep v pork belly JOMO portland paleo ennui yes plz. Offal kickstarter jawn yuccie.`,
    `Plaid marfa single-origin coffee YOLO forage gentrify artisan hexagon bitters selfies sartorial. Disrupt mumblecore enamel pin squid vice, ethical biodiesel. Truffaut sriracha scenester, hammock marfa Brooklyn next level chambray you probably haven't heard of them praxis disrupt blue bottle yes plz. Shoreditch selvage cronut ethical hoodie fit put a bird on it locavore PBR&B 3 wolf moon cliche trust fund heirloom. Brooklyn everyday carry cliche vice. Meh adaptogen skateboard, jean shorts semiotics cold-pressed yuccie pop-up salvia mustache. Yr marfa cliche waistcoat fixie viral.`,
    `Gastropub adaptogen artisan hot chicken. Single-origin coffee put a bird on it shoreditch snackwave humblebrag trust fund keytar cardigan celiac tbh authentic tilde YOLO neutra butcher. Flannel grailed retro, paleo photo booth praxis poke taxidermy tilde health goth marfa gochujang salvia humblebrag. Craft beer taxidermy adaptogen, kombucha lyft distillery semiotics tbh small batch keffiyeh yuccie fashion axe try-hard. Taxidermy post-ironic gluten-free pinterest fingerstache solarpunk leggings. Tattooed biodiesel craft beer shabby chic wolf asymmetrical. Skateboard sus salvia beard irony organic intelligentsia subway tile migas ugh seitan twee marfa.`,
    `Truffaut +1 offal gatekeep neutral milk hotel cronut bodega boys dreamcatcher heirloom deep v tote bag. Tumblr cronut pug humblebrag, lyft tofu affogato direct trade biodiesel typewriter food truck farm-to-table gluten-free VHS. Sartorial coloring book woke listicle bicycle rights paleo gluten-free post-ironic lumbersexual. You probably haven't heard of them PBR&B cray, art party knausgaard glossier hella williamsburg. Bespoke four dollar toast humblebrag intelligentsia.`,
    `Trust fund kickstarter farm-to-table viral you probably haven't heard of them normcore microdosing. Cronut chillwave gatekeep lyft vinyl ennui kitsch vape ugh bodega boys. Tumeric microdosing meh, fanny pack iPhone drinking vinegar vinyl farm-to-table quinoa locavore. Cold-pressed cred kogi single-origin coffee.`,
    `Selvage hella XOXO, cray pour-over cronut gluten-free. Kinfolk adaptogen seitan sartorial keffiyeh vape single-origin coffee vegan keytar retro beard fingerstache sus. Pinterest blog cardigan, typewriter kickstarter portland raw denim 8-bit woke. Four loko affogato mukbang pug messenger bag narwhal venmo solarpunk la croix jean shorts before they sold out mustache leggings yuccie freegan. Church-key stumptown tattooed, food truck iPhone freegan yuccie. Gastropub typewriter waistcoat poke listicle viral pour-over dreamcatcher paleo beard flexitarian semiotics JOMO lumbersexual tacos.`,
    `Actually subway tile jean shorts narwhal lo-fi woke man braid whatever viral bodega boys tattooed. Iceland raclette cupping typewriter jawn bodega boys chambray, trust fund vice chillwave same letterpress cardigan. Retro tumeric lyft kitsch roof party next level, chillwave tilde chia tofu copper mug aesthetic tattooed synth. DIY street art gatekeep, locavore flannel 90's neutral milk hotel. Occupy keytar before they sold out prism literally pickled PBR&B.`,
    `Pinterest street art austin put a bird on it flexitarian copper mug pop-up woke vegan cold-pressed knausgaard snackwave deep v la croix. Ethical fixie bushwick narwhal, readymade umami blog cray knausgaard keffiyeh migas XOXO master cleanse shoreditch. Wayfarers gochujang yes plz grailed Brooklyn. Post-ironic freegan chambray hella iPhone fit biodiesel fashion axe. Selvage marxism echo park, meditation asymmetrical mustache mlkshk bicycle rights sartorial health goth photo booth godard JOMO snackwave.`,
    `Banh mi kogi migas, big mood taxidermy ascot keytar yuccie letterpress occupy brunch live-edge offal. Schlitz chartreuse waistcoat affogato, bruh hoodie squid aesthetic raclette iceland woke fam whatever letterpress. Gatekeep etsy pinterest adaptogen vexillologist kale chips snackwave whatever cardigan irony ugh authentic pork belly actually shoreditch. Letterpress locavore YOLO trust fund, mustache cardigan church-key humblebrag post-ironic tousled JOMO tilde. Vibecession gorpcore locavore taxidermy intelligentsia cupping af ramps banjo crucifix. Same health goth selfies pinterest ascot. Drinking vinegar knausgaard asymmetrical vexillologist.`,
    `Kale chips mixtape hell of cronut bodega boys deep v edison bulb poke pok pok glossier umami DSA marfa raclette twee. Shaman locavore authentic 8-bit chillwave iceland lomo PBR&B cornhole gochujang everyday carry. Grailed ascot typewriter readymade poutine brunch stumptown master cleanse fanny pack. Selfies brunch iceland vexillologist four loko whatever blue bottle. Food truck godard chambray brunch poutine vape. Tousled edison bulb wolf 3 wolf moon.`,
    `Try-hard gentrify chartreuse authentic meh shabby chic. Blue bottle yes plz snackwave iPhone, raw denim same subway tile jawn sustainable small batch kale chips. Hashtag gatekeep four dollar toast, tousled hot chicken banh mi deep v franzen blue bottle snackwave typewriter helvetica bushwick sartorial twee. Cupping selvage vegan hot chicken, tacos flexitarian drinking vinegar grailed vaporware +1 single-origin coffee.`,
    `You probably haven't heard of them crucifix slow-carb typewriter hoodie meditation man bun listicle pug vegan praxis hell of meggings trust fund put a bird on it. Locavore mixtape street art franzen irony edison bulb lomo mukbang +1 four loko. Hell of crucifix locavore mumblecore heirloom wayfarers air plant PBR&B skateboard. Mukbang listicle tilde fixie everyday carry cupping hoodie. Kitsch banjo jean shorts helvetica.`,
    `Glossier synth craft beer brunch mukbang banjo etsy. Lumbersexual palo santo gatekeep +1 photo booth, tilde woke. Pabst vice cred etsy offal la croix snackwave paleo tacos. Taiyaki succulents semiotics tote bag, flexitarian hammock try-hard listicle lo-fi. Same la croix franzen four dollar toast, taiyaki ethical salvia.`,
    `Keytar sartorial skateboard gorpcore gatekeep kale chips tumblr edison bulb bespoke. Same gentrify 8-bit, man bun blog typewriter jean shorts fit 90's plaid truffaut organic bitters. Lyft waistcoat semiotics master cleanse schlitz, af lo-fi vaporware direct trade. Yes plz semiotics pork belly blackbird spyplane artisan. Keffiyeh unicorn stumptown schlitz seitan, pitchfork put a bird on it. Shoreditch post-ironic hashtag, cupping gluten-free sriracha venmo sustainable street art.`
  ];
  export default text;
  